name: Docker
on: 
    workflow_dispatch:
#    push:

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container:
          image: node:24.3.0-alpine
            # credentials:
            #     username: ${{ secrets.DOCKER_USERNAME }}
            #     password: ${{ secrets.DOCKER_PASSWORD }}
          env:
            API_URL: development
        #  options: --publish 80:80 --volume vol_name:/tmp --volume /host/path:/path/in/container --cpus 1
### OR
        #   ports:
        #     - 80
        #   volumes:
        #     - vol_name:/tmp
        #     - /host/path:/path/in/container

        steps:
            - name: Log Node OS Version
              run: |
                node -v
                cat /etc/os-release
            
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: List Files 
              run: |
                echo "Checking out the repository"
                ls -al
                tree .github

            - name: Log Env
              run: echo $API_URL
            - name: Container in a Step
              uses: docker://node:22.17-alpine3.21
              with: 
                entrypoint: /usr/local/bin/node
                args: -p 2 + 3
            - name: Log node version
              uses: docker://node:22.17-alpine3.21
              with: 
                args: -v

            - name: Python in step
              run: |
                   import os
                   print("Build triggered by:", os.environ.get('GITHUB_ACTOR'))
                   import datetime
                   build_id = f"1.0.{datetime.datetime.now().strftime('%Y%m%d%H%M')}"
                   print(build_id)

        

