name:  Repository Events
on: [push, pull_request,issues]

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
           echo $GITHUB_SHA
           echo $GITHUB_REF
      - name: Checkout Repository
        uses: actions/checkout@v4
