name: Matrix
on: 
    push: # keyword sample As objects but can also be in Array e.g [push, pull_request]
      branches: 
        - main

jobs:
  node-matrix:
    continue-on-error: false # # This is the default behavior, but can be set to true to continue running jobs even if one fails.
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16, 18, 20, 21]
      fail-fast: false #     This is the default behavior, but can be set to true to stop all jobs if one fails.
      # max-parallel: 3
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v