name: Matrix
on: [push]

#------- ORIGINAL --------#
# X {os: ubuntu-latest, node-version: 20, is-ubuntu: true, experimental: false}
# {os: ubuntu-latest, node-version: 18, is-ubuntu: true, experimental: false}
# {os: ubuntu-latest, node-version: 16, is-ubuntu: true, experimental: true}
# {os: windows-latest, node-version: 20, experimental: false}
# {os: windows-latest, node-version: 18, experimental: false}
# {os: windows-latest, node-version: 16, experimental: false}
# {os: macos-latest, node-version: 18}
# {os: ubuntu-latest, node-version: 17 }

jobs:
  node-matrix:
    continue-on-error: ${{matrix.experimental == true}} # This is the default behavior, but can be set to true to continue running jobs even if one fails.
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20, 18, 16]
        include:
          - os: ubuntu-latest
            is-ubuntu: true
          - os: macos-latest
            node-version: 18
          - experimental: false
          - os: ubuntu-latest
            node-version: 16
            experimental: true
          - os: ubuntu-latest
            node-version: 17
        exclude:
          - os: ubuntu-latest
            node-version: 20
      fail-fast: true # This is the default behavior, but can be set to false to continue running jobs even if one fails.
      # max-parallel: 3
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.experimental == true
        run: exit 1
      - run: node -v
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v