name: Stale Issues & PRs
on:
  schedule:
    - cron: "0 14 * * *"
    - cron: "*/5 * * * *" # JUST FOR TESTING TO SEE IF IT WORKS
  workflow_dispatch: {}

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "This is some message."
          days-before-stale:  1
          days-before-close: 7