name: Stale Issues & PRs
on:
  schedule:
    - cron: "0/5 * * * *"  # Runs every 5 minutes
    - cron: "0 14 * * *"   # Also runs daily at 2:00 PM UTC
#  workflow_dispatch: {}
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "This is some message."
          days-before-stale: 1
          days-before-close: 7