# .github/workflows/test-custom-action.yml

name: Test My Action
on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use my custom action
        uses: ./.github/actions/my-custom-action
        with:
          name: Andy

      - name: Show time from output
        run: echo "Greeted at ${{ steps.time.outputs.time }}"

