name: Work Dirs & Shell
on: 
  push:
    branches:
      - main  

jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display Working Directory & List Files
        run: |
          pwd
          ls -la
      - name: Print home directory
        run: |
          echo "Home Directory: $HOME"
          echo $GITHUB_SHA
          echo $GITHUB_WORKSPACE
          echo $GITHUB_REPOSITORY
      - name: Print Os Information
        run: |
          cat /etc/os-release
      - name: Print current user
        run: |
          echo "Current User: $(whoami)"
      # - name: Print environment variables
      #   run: |
      #     printenv
      # - name: List files in home directory
      #   run: |
      #     ls -la $HOME
  display-wd-info-widnows:
    runs-on: windows-latest
    steps:
      - name: Display Working Directory & List Files
        run: |
          ls -la
          echo "Home Directory: $HOME"
          echo $GITHUB_SHA
          echo $GITHUB_WORKSPACE
          echo $GITHUB_REPOSITORY
