name: Workflow Run
on:
  workflow_run:
    workflows: [Repository Events]
    types: [completed]
    branches: 
        - main
jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - name: Echo String
        run: echo "Workflow Run Triggered by Repository Events Completion"
#TEST Trigger